CREATE TABLE ACCOUNTS (
ID String NULL,
COL1 String NULL,
PRIMARY KEY (ID)
);
CREATE TABLE BANS (
ID String NULL,
COL1 String NULL,
COL2 String NULL,
COL3 String NULL,
COL4 Long NULL,
COL5 Long NULL,
COL6 Boolean NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CONFIG(
ID String NULL,
COL1 String NULL,
PRIMARY KEY (ID)
);

CREATE TABLE PERMUSERCHANNELS(
ID String NULL,
COL1 int NULL,
COL2 String NULL,
COL3 String NULL,
PRIMARY KEY (ID)
);

CREATE TABLE RELAYBOTS(
ID String NULL,
COL1 String NULL,
COL2 String NULL,
COL3 String NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMCOMMANDS(
ID String NULL,
COL1 int NULL,
COL2 String NULL,
COL3 String NULL,
COL4 Boolean NULL,
PRIMARY KEY (ID)
);

CREATE TABLE SERVERS(
ID String NULL,
COL1 String NULL,
PRIMARY KEY (ID)
);

CREATE TABLE IRCBLACKLISTS(
ID String NULL,
PRIMARY KEY (ID)
);

CREATE TABLE SPAMBLACKLISTS(
ID String NULL,
COL1 String NULL,
COL2 int NULL,
COL3 String NULL,
COL4 String NULL,
COL5 String NULL,
COL6 String NULL,
COL7 String NULL,
COL8 String NULL,
COL9 boolean NULL,
COL10 String NULL,
PRIMARY KEY (ID)
);

